### ISSUE TITLE
BUG: ucx cannot work

### ISSUE THREAD

**Issue by luweizheng** [xorbitsai/xorbits#439]
### Describe the bug
When setting `base_config.yml` with `oscar.numa.external_addr_scheme` from `null` to `ucx`, I got the following error:

```
Traceback (most recent call last):
  File "xorbits_query.py", line 1232, in <module>
    main()
  File "xorbits_query.py", line 1217, in main
    xorbits.init(address=args.endpoint)
  File "/home/u20200002/hpc/xorbits/python/xorbits/deploy/__init__.py", line 135, in init
    mars_new_session(**kw)
  File "/home/u20200002/hpc/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1844, in new_session
    session = SyncSession.init(
  File "/home/u20200002/hpc/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1476, in init
    isolated_session = fut.result()
  File "/fs/fast/u20200002/envs/ucx2/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/fs/fast/u20200002/envs/ucx2/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/u20200002/hpc/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 754, in init
    return await _IsolatedWebSession._init(
  File "/home/u20200002/hpc/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1228, in _init
    session_id, _ = await session_api.create_session(session_id)
  File "/home/u20200002/hpc/xorbits/python/xorbits/_mars/services/session/api/web.py", line 140, in create_session
    res = await self._request_url(path=addr, method="PUT", data=b"")
  File "/home/u20200002/hpc/xorbits/python/xorbits/_mars/services/web/core.py", line 260, in _request_url
    raise TimeoutError(str(ex)) from None
TimeoutError: Timeout during request
```

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Python 3.8.16
2. xorbits: 0+untagged.247.g039503b xoscar:  0+untagged.19.gd4ace47

### Expected behavior
ucx backend can work.

### Additional context

[The example script](https://ucx-py.readthedocs.io/en/latest/quickstart.html) from `ucx` documentation can send and receive data in my environment.

**Comment by luweizheng** [comment]
This issue was fixed by https://github.com/xorbitsai/xorbits/pull/490
We should pass the right scheme when using ucx. For example, the supervisior's URI should be: ucx://ip:port.
We should update documentation later to tell users how to use different communication scheme.
