### ISSUE TITLE
BUG: df.copy() Error

### ISSUE THREAD

**Issue by Hank0626** [xorbitsai/xorbits#443]
```python
import xorbits.pandas as pd
df = pd.DataFrame([[1, 2.12], [3.356, 4.567]])
df_copy = df.copy()
```
```
Traceback (most recent call last):
  File "/Users/lpy/Desktop/xorbits/test.py", line 3, in <module>
    df_copy = df.copy()
  File "/Users/lpy/Desktop/xorbits/python/xorbits/core/adapter.py", line 170, in _wrapped
    return member_func(mars_entity, *args, **kwargs)
  File "/Users/lpy/Desktop/xorbits/python/xorbits/core/adapter.py", line 304, in wrapped
    return from_mars(c(*to_mars(args), **to_mars(kwargs)))
  File "/Users/lpy/Desktop/xorbits/python/xorbits/_mars/core/base.py", line 97, in copy
    return self.copy_to(type(self)(_key=self.key))
TypeError: __init__() got an unexpected keyword argument '_key'
```

**Comment by UranusSeven** [comment]
Hi, thanks for reporting the issues. Could you please submit an individual issue for each of them with the issue template?

It would be easier for users and maintainers to keep track of the progress.
