### ISSUE TITLE
BUG: To many distracted messages came from monitor_sub_pools

### ISSUE THREAD

**Issue by qinxuye** [xorbitsai/xorbits#587]
### Describe the bug

The message shown below may show too much times, it's quite distracted and may bury the real error.

```
2023-07-10 11:39:51,144 xoscar.backends.pool 2887043 ERROR    Monitor sub pool 127.0.0.1:37853 failed
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.11/site-packages/xoscar/backends/pool.py", line 1342, in monitor_sub_pools
    if not await self.is_sub_pool_alive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/site-packages/xoscar/backends/indigen/pool.py", line 310, in is_sub_pool_alive
    return await asyncio.to_thread(process.is_alive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 2729, in uvloop.loop.Loop.run_in_executor
  File "/usr/local/python3/lib/python3.11/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
2023-07-10 11:39:51,146 xoscar.backends.pool 2887043 ERROR    Monitor sub pool 127.0.0.1:41267 failed
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.11/site-packages/xoscar/backends/pool.py", line 1342, in monitor_sub_pools
    if not await self.is_sub_pool_alive(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/site-packages/xoscar/backends/indigen/pool.py", line 310, in is_sub_pool_alive
    return await asyncio.to_thread(process.is_alive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 2729, in uvloop.loop.Loop.run_in_executor
  File "/usr/local/python3/lib/python3.11/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

**Comment by codingl2k1** [comment]
Related PR: https://github.com/xorbitsai/xorbits/pull/575

**Comment by codingl2k1** [comment]
This bug has been fixed by this PR: https://github.com/xorbitsai/xoscar/pull/37. I think we should pin a higher version of xoscar. Can you try to upgrade the xoscar to 0.0.8?

**Comment by qinxuye** [comment]
Yeah, we should bump the minimal version of xoscar.
