### ISSUE TITLE
BUG: GPU cudf TPC-H Query 8 fails

### ISSUE THREAD

**Issue by luweizheng** [xorbitsai/xorbits#821]
### Describe the bug
GPU cudf TPC-H Query 8 fails with the following error:

```
Traceback (most recent call last):
  File "../df-eval/tpch/xorbits_queries/queries.py", line 1574, in run_queries
    xorbits.run(result)
  File "../hpc/xorbits/python/xorbits/core/execution.py", line 55, in run
    mars_execute(mars_tileables, **kwargs)
  File "../hpc/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1789, in execute
    return session.execute(
           ^^^^^^^^^^^^^^^^
  File "../hpc/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1600, in execute
    execution_info: ExecutionInfo = fut.result(
                                    ^^^^^^^^^^^
  File "/fs/fast/u20200002/envs/xor/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/fs/fast/u20200002/envs/xor/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "../hpc/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1769, in _execute
    await execution_info
KeyError: "Field 'NATION' was not found in record with fields ('VOLUME',)"
```

**Comment by hucorz** [comment]
Due to cudf’s strict limitations on udf usage, Query8 need to rewrite the code to achieve the same result without using udf.

**Original Code:**
```
def udf(df):
    denominator = df["VOLUME"].sum()
    df = df[df["NATION"] == nation_name]
    numerator = df["VOLUME"].sum()
    return numerator / denominator

total = total.groupby("O_YEAR").apply(udf, include_groups=False).reset_index()
total.columns = ["O_YEAR", "MKT_SHARE"]
total = total.sort_values(by=["O_YEAR"], ascending=[True])
```
**New Code:**
```
total1 = df_total.groupby("O_YEAR", as_index=False).agg('sum')
total2 = df_BRAZIL.groupby("O_YEAR", as_index=False).agg('sum')
final_total = total1.merge(total2, on="O_YEAR", how="left", suffixes=('_all', '_brazil'))
final_total["ratio"] = final_total["VOLUME_brazil"] / final_total["VOLUME_all"]
final_total = final_total[["O_YEAR", "ratio"]]
final_total.columns = ["O_YEAR", "MKT_SHARE"]
total = final_total.sort_values(by=["O_YEAR"], ascending=[True])
```
